### ISSUE TITLE
Unable to connect to Kubernetes cluster using certificate authentication

### ISSUE THREAD

**Issue by anadale** [JetBrains/teamcity-kubernetes-plugin#21]
After setting KUBERNETES_TRUST_CERTIFICATES environment variable and filling in certificate into appropriate field click on "Test Connection" pops up an error message saying:

Connection failed!
Error connecting to https://xxx.com: Failure executing: GET at: https://xxx.com/api/v1/namespaces/default. Message: Unauthorized

What am I doing wrong?

**Comment by ekoshkin** [comment]
@anadale what kubernetes engine and teamcity plugin versions do you use?

**Comment by anadale** [comment]
TeamCity 2017.2 (build 50574) (Docker container), Kubernetes support snapshot-20171130142233.

**Comment by ekoshkin** [comment]
Please save this profile, try to run cloud instance from it and send me resulted server logs

**Comment by anadale** [comment]
An attempt to save a profile gives me the following error:

```Failed to initialize cloud client 'kube'.Failure executing: GET at: https://controllers.k8s.digillect.com/api/v1/namespaces/tectonic-system/pods?labelSelector=teamcity-cloud-image%3D1. Message: Unauthorized. Received status: Status(apiVersion=v1, code=401, details=null, kind=Status, message=Unauthorized, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Unauthorized, status=Failure, additionalProperties={}).```

Stacktrace:

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://controllers.k8s.digillect.com/api/v1/namespaces/tectonic-system/pods?labelSelector=teamcity-cloud-image%3D1. Message: Unauthorized. Received status: Status(apiVersion=v1, code=401, details=null, kind=Status, message=Unauthorized, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Unauthorized, status=Failure, additionalProperties={}).
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:583)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:68)
at jetbrains.buildServer.clouds.kubernetes.connector.KubeApiConnectorImpl.listPods(KubeApiConnectorImpl.java:76)
at jetbrains.buildServer.clouds.kubernetes.KubeCloudImageImpl.populateInstances(KubeCloudImageImpl.java:138)
at jetbrains.buildServer.clouds.kubernetes.KubeCloudClientFactory.lambda$createNewClient$0(KubeCloudClientFactory.java:101)
at jetbrains.buildServer.util.CollectionsUtil.filterAndConvertCollection(CollectionsUtil.java:143)
at jetbrains.buildServer.util.CollectionsUtil.filterAndConvertCollection(CollectionsUtil.java:127)
at jetbrains.buildServer.util.CollectionsUtil.filterAndConvertCollection(CollectionsUtil.java:111)
at jetbrains.buildServer.util.CollectionsUtil.convertCollection(CollectionsUtil.java:250)
at jetbrains.buildServer.clouds.kubernetes.KubeCloudClientFactory.createNewClient(KubeCloudClientFactory.java:99)
at jetbrains.buildServer.clouds.server.impl.ProjectCloudManagerImpl.createNewClient(ProjectCloudManagerImpl.java:384)
at jetbrains.buildServer.clouds.server.impl.ProjectCloudManagerImpl.getClient(ProjectCloudManagerImpl.java:303)
at jetbrains.buildServer.clouds.server.impl.CloudManagerBaseImpl.getClient(CloudManagerBaseImpl.java:408)
at jetbrains.buildServer.clouds.server.impl.CloudManagerFacade.getClient(CloudManagerFacade.java:146)
at jetbrains.buildServer.clouds.server.impl.SecuredCloudManager.getClient(SecuredCloudManager.java:111)
at jetbrains.buildServer.clouds.server.web.beans.CloudTabFormFactoryImpl$CreateProfileInfo.tryCreateInfo(CloudTabFormFactoryImpl.java:122)
at jetbrains.buildServer.clouds.server.web.beans.CloudTabFormFactoryImpl$CreateProfileInfo.createInfo(CloudTabFormFactoryImpl.java:107)
at jetbrains.buildServer.clouds.server.web.beans.CloudTabFormFactoryImpl.createProfileInfo(CloudTabFormFactoryImpl.java:87)
at jetbrains.buildServer.clouds.server.web.beans.CloudTabFormFactoryImpl.getForm(CloudTabFormFactoryImpl.java:77)
at jetbrains.buildServer.clouds.server.web.project.CloudProfilesProjectTab.fillModel(CloudProfilesProjectTab.java:93)
at sun.reflect.GeneratedMethodAccessor204.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at jetbrains.buildServer.web.impl.PagePlaceImpl$ProxyHandler.invokeExtensionMethodUnsafe(PagePlaceImpl.java:24)
at jetbrains.buildServer.web.impl.PagePlaceImpl$ProxyHandler.invoke(PagePlaceImpl.java:2)
at com.sun.proxy.$Proxy61.fillModel(Unknown Source)
at jetbrains.buildServer.web.impl.PageExtensionsInterceptor.fillModel(PageExtensionsInterceptor.java:15)
at jetbrains.buildServer.web.impl.PageExtensionsInterceptor.processCustomTabs(PageExtensionsInterceptor.java:12)
at jetbrains.buildServer.web.impl.PageExtensionsInterceptor.fillModel(PageExtensionsInterceptor.java:80)
at jetbrains.buildServer.web.impl.PageExtensionsInterceptor.postHandle(PageExtensionsInterceptor.java:24)
at org.springframework.web.servlet.HandlerExecutionChain.applyPostHandle(HandlerExecutionChain.java:151)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:974)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.processedByMainServlet(TeamCityDispatcherServlet.java:34)
at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:25)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at jetbrains.buildServer.web.jsp.JspPrecompilerFilter.doFilter(JspPrecompilerFilter.java:127)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at jetbrains.buildServer.web.DisableSessionIdFromUrlFilter.doFilter(DisableSessionIdFromUrlFilter.java:6)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
at jetbrains.buildServer.diagnostic.web.DiagnosticFilter.doFilter(DiagnosticFilter.java:38)
at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
at jetbrains.buildServer.web.DependencyParametersCalculationContextFilter.doFilter(DependencyParametersCalculationContextFilter.java:13)
at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
at jetbrains.buildServer.web.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:9)
at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
at jetbrains.buildServer.web.CSRFFilter.doFilter(CSRFFilter.java:100)
at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
at jetbrains.buildServer.web.DelegatingFilter.doFilter(DelegatingFilter.java:37)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at jetbrains.buildServer.web.ResponseFragmentFilter.doFilter(ResponseFragmentFilter.java:8)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by anadale** [comment]
Any news with this issue?

**Comment by ekoshkin** [comment]
@anadale please try to specify KUBERNETES_CERTS_CA_FILE or KUBERNETES_CERTS_CA_DATA environment variables in advance. KUBERNETES_CERTS_CA_DATA should contain base64 encoded string.
By the way I've built new plugin verision with fabric8io client updated to the latest release. https://teamcity.jetbrains.com/viewLog.html?buildId=1366064&buildTypeId=TeamCityPluginsByJetBrains_TeamCityKubernetesPlugin_Build20172x&tab=artifacts
Please try it, it might help if specifying additional env vars will not help.

**Comment by anadale** [comment]
@ekoshkin I've updated plugin and tried to set "env.KUBERNETES_CERTS_CA_DATA" environment variable with encoded CA certificate. Nothing has changed :-(

**Comment by ekoshkin** [comment]
@anadale make sure you follow these instructions to import certificate https://kubernetes.io/docs/concepts/cluster-administration/certificates/

**Comment by anadale** [comment]
@ekoshkin Here is what I did:

- I've taken the value of key clusters/cluster/certificate-authority-data from ~/.kube/config and added it as "env.KUBERNETES_CERTS_CA_DATA" parameter in project settings page, section "Parameters", under "Environment variables"
- I've taken the value of key users/user/client-certificate-data from ~/.kube/config and copied it into "Client certificate" field selecting "Authentication strategy" as "Client certificate"

Clicking on "Test connection" gives me the following error:

Error connecting to https://controllers.k8s.digillect.com:443/: Failure executing: GET at: https://controllers.k8s.digillect.com/api/v1/namespaces/default. Message: Unauthorized. Received status: Status(apiVersion=v1, code=401, details=null, kind=Status, message=Unauthorized, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Unauthorized, status=Failure, additionalProperties={}).

**Comment by ekoshkin** [comment]
I think the problem here is that client-certificate-data in config is already besa64 encoded, and plugin encodes it second time when passing Client Certificate field value to API.

**Comment by ekoshkin** [comment]
By the way, i ve added support of CA cert in plugin, so now you can export CA cert from cluster and use to setup valid TLS connection.

**Comment by anadale** [comment]
Yes, it worked out! Thank you very much.
